### ISSUE TITLE
Fix characters encoding?

### ISSUE THREAD

**Issue by hohmd** [reillychase/pvpgn-html5-chat-client#1]
It seems like it supports only english chars now.

Other languages displayed like:
```html
<chucha> \377 \357\356\362\356\354 \355\345 \361\354\356\343\363
<Jlec> \352\340\352\356\351 \367\340\354\357?
<chucha> \362\345\354\341\356\353\345\345 \377 \355\345 \360\340\347\356\343\360\345\362
<chucha> \355\363 \353\345\361\355\350\352\356\342\373\351\\
<Jlec> \356\365
<chucha> \343\356
```

Can you make it UTF-8?

**Comment by reillychase** [comment]
Yes this is a top priority because I know the PvPGN community is very diverse, I haven't got it working yet.

At the bottom of the readme is a list of things that need improvement at the moment, as you see unicode is the top of the list.

**Comment by reillychase** [comment]
Unicode support working now!
